name: "Build WIP Hysteria 2"

on:
  push:
    branches:
      - 'wip-hy2'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup Python # This is for the build script
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run build script
        env:
          HY_APP_PLATFORMS: 'windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64'
        run: 'python hyperbole.py build -r'

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: hy2-wip-${{ github.sha }}
          path: build